name: CI

on:
  pull_request:
    on: [push, pull_request]

jobs:
  webapp:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Check lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: KarakoA/setup-neo4j@v1.1.1
        with:
          tag: '4.2.1'
          passwort: NEO4J
      
      - name: Install Dependencies
        run: npm install

      - name: Check lint
        run: npm run lint

      - name: Run Tests
        run: npm run test
